<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net9.0;net10.0</TargetFrameworks>
    <Authors>Passingwind</Authors>
    <Version>0.2.0</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/jxnkwlp/NginxConfigParser</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jxnkwlp/NginxConfigParser</RepositoryUrl>
    <RepositoryType>Github</RepositoryType>
    <PackageTags>nginx, nginx config</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A .net standard library for reading and writing nginx configuration files.</Description>
    <Copyright>Passingwind</Copyright>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DocumentationFile>bin\NginxConfigParser.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
